# Generated by Django 5.2.17 on 2026-09-26 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(default='mercadopago', max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('qr_code', models.TextField(blank=True)),
                ('qr_code_base64', models.TextField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
